headers: (0,0);(0,1);(0,2);(0,3);(0,4);(0,5)

import pandas as pd

df = pd.DataFrame({
    'Study Type': ['Animal, in-vivo', 'Animal, in-vivo', 'Animal, in-vivo', 'Animal, in-vivo', 'Animal, in-vivo', 'Animal, in-vivo', 'Animal, in-vivo', 'Animal, in-vivo', 'Animal, in-vivo', 'Animal, in-vitro and in-vivo', 'Animal, in-vivo', 'Animal, in-vivo', 'Human, in-vitro', 'Animal, in-vivo Human, in-vivo', 'Human, in-vivo', 'Human, in-vivo', 'Human, in-vivo', 'Human, in-vivo'],
    'Disease or Model': ['BMT', 'Bleomycin fibrosis', 'BMT', 'Radiation pneumonitis', 'BMT', 'BMT and parabiotic animals', 'Bleomycin fibrosis', 'Radiation fibrosis', 'BMT', 'Hypoxia-induced pulmonary hypertension', 'Ablative radiation and elastase induced emphysema', 'Bleomycin fibrosis', 'Heat shock in cell culture', 'OVA-sensitized mouse model Allergen – sensitized asthmatics', 'Human heart and lung transplant', 'Human lung transplant Human BMT', 'Human BMT', 'Human BMT'],
    'Tissue of Origin': ['MSC', 'MSC', 'HSC enrichment', 'Whole bone marrow', 'Whole bone marrow/EGFP retrovirus', 'HSC', 'MSC', 'MSC or whole bone marrow', 'Bone marrow, EGFP labeled', 'Circulating BM-derived c-kit positive', 'GFP + fetal liver', 'Whole marrow GFP +', 'MSC and SAEC', 'CD34 positive, collagen I expressing fibrocytes CD34 positive, collagen I expressing fibrocytes', 'Sex-mismatched donor lung or heart', 'Sex-mismatched donor lung Sex-mismatched donor bone marrow', 'Sex-mismatched donor bone marrow', 'Sex-mismatched donor bone marrow'],
    'Lung Cell Type Formed / Frequency': ['Undefined mesenchymal cells / occasional', 'Type I pneumocytes / rare', 'Type II pneumocytes / up to 20%, bronchial epithelium / 4%', 'Type II pneumocytes, bronchial epithelium / up to 20% of type II cells', 'Type II pneumocytes / 1–7%', 'Hematopoietic chimerism but exceedingly rare lung cell types', 'Type II pneumocytes / ~1%', 'Fibroblasts / common', 'Fibroblasts, Type I pneumocyte / occasional to rare', 'c-kit positive cells in pulmonary artery vessel wall; In hypoxia, circulating cells generate endothelial and smooth muscle cells in-vitro', 'Alveolar epithelium and endothelium; frequency not reported but increased by G-CSF and retinoic acid', 'GFP + type I collagen expressing', 'Cell fusion / common', 'Myofibroblasts / ? Myofibroblasts / ?', 'No lung cell types of recipient origin', 'Bronchial epithelium, type II pneumocytes, glands of recipient origin / 9 – 24% No lung cell types of donor origin', 'Lung epithelium and endothelium of donor origin / up to 43%', 'No nasal epithelium of donor origin'],
    'Method of Detection': ['PCR for collagen gene marker', 'β galactosidase protein', 'Y chromosome FISH, surfactant B mRNA', 'Y chromosome FISH, surfactant B mRNA', 'EGFP, keratin immunostain, surfactant protein B FISH', 'EGFP', 'Y chromosome FISH', 'EGFP, Y chromosome FISH, vimentin immunostain', 'Flow cytometry', 'Flow cytometry and immunohistochemistry', 'Immunohistochemistry for CD45 - , GFP + cells', 'Flow cytometry and immunohistochemistry, RT-PCR', 'Immunostaining, microarray', 'CD34-positive, collagen I, α-smooth muscle actin CD34-positive, collagen I, α-smooth muscle actin', 'X and Y chromosome FISH, antibody stain for hematopoeitic cells', 'Y chromosome FISH, short tandem repeat PCR Y chromosome FISH, short tandem repeat PCR', 'X and Y chromosome FISH, keratin and PECAM immunostain', 'Y chromosome FISH, cytokeratin immunostain'],
    'Ref.': ['[30]', '[23]', '[31]', '[25]', '[33]', '[32]', '[22]', '[26]', '[34]', '[27]', '[28]', '[24]', '[39]', '[29]', '[36]', '[35]', '[38]', '[37]'],
}, index=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17])
