headers: (0,0);(0,1);(0,2);(0,3)

import pandas as pd

df = pd.DataFrame({
    'Factor': ['Professional Role Modeling', '', '', '', '', '', 'Teaching', '', '', '', '', '', '', '', '', '', 'Learning Climate', '', '', '', '', '', '', 'Feedback', '', '', 'Direction', '', '', '', '', 'Patient Presence', '', 'Health Care System Interaction', ''],
    'Items Making Up Factor': ['Provides a role model of professional behaviour', 'Demonstrates effective interactions with support staff', 'Provides a role model of a balance between personal and professional life', 'Teaches communication skills', 'Discusses limitations of his or her own knowledge', 'Discusses own clinical reasoning processes', 'Discusses clinical topics in an organized way', 'Discusses clinical topics concisely', 'Suggests relevant reading', "Identifies and responds to student's specific learning needs", 'Is open to questions', 'Asks students differing complexities of questions', 'Has a strong command of his or her area of specialty', "Asks for students' ideas before giving own", 'Sets time aside to discuss topics unable to be discussed during busy clinics', 'Monitors quality of the rotation', 'Makes student feel like a valued member of the practice', 'Demonstrates a caring attitude towards students', "Seeks to understand student's ideas", 'Demonstrates a caring attitude towards patients', 'Demonstrates enthusiasm for teaching', 'Welcomes differing points of view', "Facilitates student's participation in follow-up care", 'Gives constructive feedback', 'Gives timely feedback', 'Reviews differential diagnosis', 'Outlines specific task(s) to be done during a clinical encounter', 'Focuses on one teaching theme per clinic', 'Provides background on patients before student sees patient', 'Teaches physical examination', "Defines student's role", "Teaches in the patient's presence", "Reviews case in the patient's presence", 'Teaches use of community resources', 'Teaches appropriate use of health care resources'],
    'Factor Loading': ['.681', '.565', '.557', '.526', '.500', '.426', '.739', '.650', '.462', '.390', '.365', '.362', '.340', '.334', '.323', '.301', '.613', '.591', '.563', '.512', '.365', '.328', '.301', '.730', '.709', '.473', '.588', '.507', '.447', '.432', '.404', '.759', '.720', '.531', '.516'],
    'Alpha Analysis': ['.79', '', '', '', '', '', '.82', '', '', '', '', '', '', '', '', '', '.83', '', '', '', '', '', '', '.73', '', '', '.69', '', '', '', '', '.77', '', '.82', ''],
}, index=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])
