headers: (0,0);(0,1);(0,2);(0,3);(0,4);(0,5);(0,6);(0,7);(0,8)

import pandas as pd

df = pd.DataFrame({
    'Tumor No.': ['06', '15', '24', '25', '27', '29', '32', '34', '40', '48', '68', '76', '78', '79', '80', '82', '83', '85', '88', '95', '98', '99', '102', '123', '209', '221', '248', '311', '326', '341', '345', '360', '400', '423', '425', '474', '591', '193a', '196a', '274b', '295b', '464c', '501c', '606c', '481d', '527d', '204e', '226e'],
    'Sex': ['Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', '15', 'Female', 'Female', 'Male', 'Female', 'Male', 'Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Male', 'Female', 'Female', 'Male', 'Female', 'Female', 'Female', 'Female', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female'],
    'Age-Dx': ['7', '35', '16', '8', '34', '19', '25', 'Femur', '11', '32', '18', '20', '5', '9', '46', '23', '12', '34', '17', '71', '31', '22', '70', '16', '17', '17', '13', '13', '20', '12', '10', '18', '15', '30', '24', '17', '15', '17', '15', '13', '13', '15', '15', '14', '10', '10', '18', '18'],
    'Site': ['Distal Femur', 'Distal Femur', 'Clavicle', 'Skull', 'Ischium', 'Ilium', 'Ilium', 'Chndroblastic And Osteoblastic', 'Left Distal Femur', 'Proximal Tibia', 'Femur', 'Thigh', 'Humerus', 'Tibia', 'Tibia', 'Humerus', 'Femur', 'Femur', 'Humerus', 'Femur', 'Ilium', 'Humerus', 'Humerus', 'Femur', 'Distal Femur', 'Femur', 'Tibia', 'Distal Femur', 'Femur', 'Lemur', 'Distal Femur', 'Distal Femur', 'Distal Femur', 'Proximal Humerus', 'Tibia', 'Pelvis', 'Proximal L Tibia', 'Distal Femur', 'Distal Femur', 'Distal Femur', 'Femur', 'Distal Femoral Head', 'Femur', 'Distal Femur', 'Distal Femur', 'Proximal Tibia', 'Distal Femur', 'Distal Femur'],
    'Histological Subtype': ['NA', 'Osteoblastic+MFH-Like', 'Chondroblastic', 'Osteoblastic', 'Mixed Chondroblastic+Fibroblastic-Like', 'NA', 'Chondroblastic', 'Biopsy', 'Giant Cell', 'Osteo/Fibro/Chondroblastic', 'Telangectactic', 'N/A', 'N/A', 'Telangectactic', 'N/A', 'Osteoblastic', 'Telangiectatic', 'Fibroblastic', 'Chndorblastic', 'Giant Cel Rich', 'Epithelioid', 'N/A', 'Fibrohistiocytic', 'N/A', 'Osteoblastic', 'Osteoblastic', 'Pleiomorphic', 'Osteoblastic', 'Osteoblastic', 'Fibroblastic', 'Osteosarcoma', 'Osteoblastic', 'Chondroblastic', 'Giant Cell', 'N/A', 'Chondroblastic', 'Telangectactic', 'Osteoblastic', 'Osteoblastic', 'Osteoblastic//Chondroblastic', 'Osteoblastic//Chondroblastic', 'Osteoblastic/Spindle Cell/Chondroblastic', 'Osteoblastic', 'Osteoblastic', 'Osteoblastic', 'Osteoblastic', 'Osteoblastic', 'Telangectactic'],
    'Type': ['Biopsy', 'Biopsy', 'Biopsy', 'Mets', 'Mets', 'Biopsy', 'Biopsy', 'L', 'Definitive', 'Definitive', 'Mets', 'Biopsy', 'Biopsy', 'Mets', 'Biopsy', 'Mets', 'Biopsy', 'Biopsy', 'Biopsy', 'Biopsy', 'Biopsy', 'Biopsy', 'Mets', 'Biopsy', 'Biopsy', 'Biopsy', 'Biopsy', 'Definitive', 'Pul Met', 'Biopsy', 'Biopsy', 'Biopsy', 'Yes', 'Definitive', 'Biopsy', 'Biopsy', 'Definitive', 'Biopsy', 'Pul Met', 'Biopsy', 'Yes', 'Biopsy', 'Definitive', 'Biopsy', 'Biopsy', 'Definitive', 'Biopsy', 'Definitive'],
    'Metastatic Disease': ['L', 'L', 'L', 'L', 'L', 'M', 'L', 'II', 'None', 'None', '', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'No', 'No', 'No', 'No', 'Yes', 'N', 'No', 'Yes', '', 'None', 'Proximal Femur', 'None', 'No', 'No', 'Yes', 'No', 'II', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No'],
    'Huvos Grade': ['II', '', 'Minimal', '', '', 'II', 'Minimal', 'PR', 'IV', 'I', '', '', 'III', 'III', 'I', 'I', 'IV', 'I', 'IV', '', '', '', '', 'I', 'II', 'IV', '?', 'III', 'IV', 'II', 'IV', 'IV', '', 'I', 'I', 'II', 'II', '', '', 'II', 'PR', 'II', 'II', 'II', 'II', 'III', 'I', 'I'],
    'Response': ['PR', '', '', '', '', 'PR', '', '', 'GR', 'PR', '', '', 'GR', 'GR', 'PR', 'PR', 'GR', 'PR', 'GR', '', '', '', '', 'PR', 'PR', 'GR', '', 'GR', 'GR', 'PR', 'GR', 'GR', '', 'PR', 'PR', 'PR', 'PR', '', '', 'PR', '', 'PR', 'PR', 'PR', 'PR', 'GR', 'PR', 'PR'],
}, index=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])
