headers: (0,0);(0,1);(0,2)

import pandas as pd

df = pd.DataFrame({
    '': ['Labelled correctly', 'Mislabelled as a different ethical issue or subset of Autonomy not defined', '[Labelled correctly] + [mislabelled]', 'Total number of issues identified as ethical which were not ethical issues', 'Labelled correctly', 'Labelled as Autonomy, no subsection specified', 'Mis-labelled as a different ethical issue', 'Labelled correctly', 'Labelled as Autonomy, no subsection specified', 'Mis-labelled as a different ethical issue', 'Labelled correctly', 'Labelled as Autonomy, no subsection specified', 'Mis-labelled as a different ethical issue', 'Labelled correctly', 'Labelled as Autonomy, no subsection specified', 'Mis-labelled as a different ethical issue', 'Labelled correctly', 'Labelled as Autonomy, no subsection specified', 'Mis-labelled as a different ethical issue', 'Labelled correctly', 'Labelled as Autonomy, no subsection specified', 'Mis-labelled as a different ethical issue', 'Labelled correctly', 'Labelled as Autonomy, no subsection specified', 'Mis-labelled as a different ethical issue', 'Labelled correctly', 'Labelled as Autonomy, no subsection specified', 'Mis-labelled as a different ethical issue', 'Labelled correctly', 'Mis-labelled as a different ethical issue', 'Labelled correctly', 'Mis-labelled as a different ethical issue', 'Labelled correctly', 'Mis-labelled as a different ethical issue'],
    'Median': ['2', '2', '4', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
    'Range': ['2 – 7', '3 – 9', '2 – 9', '0–4', '0–4', '0–3', '0–3', '0–1', '0–1', '0–1', '0–1', '0–1', '0 – 0', '0 – 2', '0 – 1', '0 – 1', '0 – 0', '0 – 1', '0 – 0', '0 – 1', '0 – 1', '0 – 1', '0 – 1', '0 – 1', '0 – 2', '0 – 2', '0 – 2', '0 – 2', '0 – 2', '0 – 1', '0 – 2', '0 – 3', '0 – 1', '0 – 2'],
}, index=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])
