headers: (0,0);(0,1);(0,2);(0,3)

import pandas as pd

df = pd.DataFrame({
    '': ['Coppoolse 1999 [10]', 'Vogiatzis 2002 [11]', 'Kaelin 2001 [12]'],
    'Population': ['21 stable male COPD patients (mean age 65 years, FEV1 36.8% predicted)', '45 stable COPD patients (62% males, (mean age 65 years, FEV1 34.1% predicted)', '19 stable COPD patients (89% males) (mean age 67 years, FEV1 26.9% predicted)'],
    'Exercise protocols and rehabilitation program': ['Group 1 : CT ergometer cycling at 60% of Wmax Group 2 : IT ergometer cycling at 90% of Wmax (1 min) and 45% of Wmax (2 min) 3 days/week plus CT ergometer cycling at 60% of Wmax 2 days/week 8 weeks inpatient rehabilitation with 5 exercise sessions per week of 30 min. No additional physical exercise.', 'Group 1 : CT ergometer cycling at 50% of Wmax weeks 1–4, at 60% weeks 5–8 and at 70% weeks 9–12 Group 2 : IT ergometer cycling at 100% of Wmax (30 sec) and 45% of Wmax (30 sec) weeks 1–4, at 120% weeks 5–8 and at 140% weeks 9–12 12 weeks outpatient rehabilitation with 2 exercise sessions per week of 40 min. No additional physical exercise.', 'Group 1 : CT walking on stepper (70 steps/minute) or treadmill (1.5 miles/hour). Increase of 1 MET every 2 weeks Group 2 : IT walking on stepper (70 steps/minute) or treadmill (1.5 miles/hour) with active rest to ratio of 2:1. Increase of 1 MET every 2 weeks 6 weeks outpatient rehabilitation with 3 exercise sessions per week of 10–30 min. Additional resistance training and flexibility training.'],
    'Main results': ['Significant increase of V O2 and decrease of minute ventilation with CT but no changes with IT. Significant increase of Wmax and decrease of leg pain during exercise with IT but not with CT. Only significant differences between CT and IT for V O2 /Wmax favouring CT. 91% of patients with CT and 90% of patients with IT completed the exercise program.', 'Significant improvements of CRQ scores and Wmax and reductions of minute ventilation during CWRT in both groups. No significant differences between groups. Attendance rate for exercise sessions 88% for CT and 90% for IT.', 'Larger improvements of 6-minute walking distance with IT (80 meters) compared with CT (39 meters). No data on compliance.'],
}, index=[0, 1, 2])
