import pandas as pd

df = pd.DataFrame({
    'Tag sequence': ['', 'TGGGATTCCC', 'ATCTGCTCGG', 'GTCAGAACTT', 'GTACGGAGAT', '', 'TGGGATTCCC', 'GTGCGGAGGA', 'TTTGCACTTT', 'CCATTGTGGA', 'ATCTGCTCGG', 'CGCGGCGGCG', 'CCCAGTAAGA', 'GTACGGAGAT', '', 'ACTGTCGCCA', 'ATGTAGAGTG', 'CTCAGCAATG', 'GTCAACAGTA', 'GTGCGGAGGA', 'TGGGATTCCC', 'ATCTGCTCGG', 'GTTTATGGAT'],
    'Symbol': ['', 'CHI3L2', 'NMB', '', 'VCAM1', '', 'CHI3L2', 'SAA1', 'SMOC1', 'ADORA3', 'NMB', 'CRF', 'CSRP2', 'VCAM1', '', 'AQP1', 'TYMS', 'TOP2A', 'ABCC3', 'SAA1', 'CHI3L2', 'NMB', 'MGP'],
    'Gene/Ontology': [' Low grade astrocytomas (grade II) ', 'Chitinase 3-like 2 / cartilage biogenesis, extra-cellular', 'Neuromedin B / signal transduction, neuropeptide', 'cDNA FLJ22528 / unknown', 'Vascular cell adhesion molecule 1/ cell adhesion', ' Anaplastic astrocytomas (grade III) ', 'Chitinase 3-like 2 / cartilage biogenesis, extra-cellular', 'Serum amyloid A1/ inflammatory response, lipid metabolism, extra-cellular', 'Secreted modular calcium-binding 1/ calcium ion binding', 'Adenosine A3 receptor / signal transduction, G-protein coupled receptor', 'Neuromedin B/ signal transduction, neuropeptide', 'C1q-related factor / function unknown', 'Cysteine and glycine-rich protein 2 / cell differentiation/growth, LIM domain protein', 'Vascular cell adhesion molecule 1/ cell adhesion', ' Glioblastomas (grade IV) ', 'aquaporin 1 / water transport, ion channel', 'thymidylate synthetase / pyrimidine metabolism', 'topoisomerase (DNA) II alpha (170 kD) / DNA metabolism, isomerase', 'ATP-binding cassette, subfamily C, member 3/ multidrug resistance, transport protein', 'serum amyloid A1/ inflammatory response, lipid metabolism, extra-cellular', 'chitinase 3-like 2 / cartilage biogenesis, extra-cellular', 'Neuromedin B / signal transduction, neuropeptide', 'Matrix Gla protein /cartilage condensation, ossification, extra-cellular'],
    'Mean tumor a': ['', '10.8', '9.1', '5.8', '4.4', '', '12.3', '11.4', '6.0', '4.1', '9.1', '7.8', '9.4', '3.0', '', '5.8', '7.1', '4.2', '12.3', '14.3', '31.3', '4.6', '7'],
    'Mean normal b': ['', '0', '0.1', '0.3', '0.2', '', '0', '0', '0', '0.1', '0.1', '0.1', '0.2', '0.2', '', '0', '0', '0', '0', '0', '0', '1', '2'],
    '% SAGE c': ['', '25', '38', '38', '50', '', '30', '20', '50', '60', '40', '70', '80', '20', '', '22', '67', '44', '89', '44', '67', '44', '56'],
    '% RT-PCR d': ['', '57', '57', '43', '29', '', '63', '50', '50', '50', '81', '56', '44', '69', '', '53', '71', '88', '94', '53', '100', '53', '35'],
}, index=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])
