import pandas as pd

df = pd.DataFrame({
    'Tag Sequence': ['', 'AAGCCGAAGA', 'CTGGGGAGTG', 'GCAACAGCAA', 'TTAATCTGAG', 'ATCTTGTTAC', 'GGAACAAACA', 'AGGGAGGGGC', 'GTATGGGCCC', 'ACGAGGGGTG', 'CACTTGAAAA', 'GATAACTACA', 'TCCTGTAAAG', 'GTCTTAAAGT', '', 'GTATGGGCCC', 'GACCACCTTT', 'ACCAAAAACC', 'AGTGGTGGCT', 'CTGGGGAGTG', 'ACATTCTTTT', 'ATCTTGTTAC', 'GCAACAGCAA', 'TCACCAAAAA', 'CACTTGAAAA', 'TTTTCAAATA', 'GTCTTTCTTG', 'GGAAATGTCA', 'GTACTAGTGT', 'AAGCTGTATA', 'GTGCTAAGCG', 'CATATCATTA', 'AACACAGCCT'],
    'Tumor a': ['', '10', '8.1', '80.9', '6.9', '11', '11.9', '32.9', '26.8', '71.4', '6.9', '6.7', '6.8', '41.8', '', '144.2', '17.3', '115.8', '14.8', '13.2', '38.2', '21.1', '97.9', '19.3', '11.6', '15.4', '24.4', '12.6', '23.8', '16.7', '10.8', '151.6', '24.9'],
    'Induction b': ['', '40', '22', '19', '18', '15', '14', '14', '13', '12', '11', '11', '11', '10', '', '72', '69', '49', '39', '35', '34', '28', '23', '19', '19', '15', '14', '13', '12', '12', '11', '11', '11'],
    'Gene': [' Anaplastic astrocytomas (Grade III) ', 'GFAP glial fibrillary acidic protein', 'VAPB VAMP associated protein B and C', 'SEC61G Sec61 gamma subunit', 'ARHGEF6', 'FN1 fibronectin 1', 'CD24', 'GPX3 glutathione peroxidase 3', 'CHI3L1 chitinase 3-like 1', 'BCAN, chondroitin sulfate proteoglycan', 'CALU calumenin', 'IGFBP7', 'CAV1 caveolin 1, 22 kDa', 'SOD2', ' Glioblastomas (grade IV) ', 'CHI3L1 chitinase 3-like 1', 'MFAP2 microfibrillar-associated protein 2', 'COL1A1 collagen, type I, alpha 1', 'FMOD fibromodulin', 'VAPB VAMP associated protein B and C', 'GPNMB glycoprotein nmb', 'FN1 fibronectin 1', 'SEC61G Sec61 gamma subunit', 'STAB1 stabilin 1', 'CALU calumenin', 'T1A-2 lung type-I', 'RAB13', 'MMP2 matrix metalloproteinase', 'CCL2 chemokine (C-C motif) ligand 2', 'TNC tenascin C (hexabrachion)', 'COL6A2 collagen, type VI, alpha 2', 'IGFBP7', 'C4A complement component 4A'],
    'Gene Ontology': ['', 'Major intermediate filament protein of mature astrocytes', 'Type IV membrane protein in plasma and intracellular vesicle membranes', 'Endoplasmatic reticulum membrane protein, translocation', 'Rac/Cdc42 guanine nucleotide exchange factor (GEF) 6, intra-cellular', 'Extra-cellular matrix, cell adhesion, cell migration', 'Plasma membrane, small cell lung carcinoma cluster 4 antigen', 'Extra-cellular, response to oxidative stress, glutathione metabolism', 'Cartilage glycoprotein', 'Cell adhesion', 'Endoplasmatic reticulum, calcium ion binding', 'Extra-cellular, insulin-like growth factor binding protein 7', 'Plasma membrane, caveolae protein, integrin-mediated celladhesion, vesicular trafficking', 'Superoxide dismutase, mitochondrial, erythropoietin-mediated neuro protection through NF-kB', '', 'Cartilage glycoprotein', 'Major antigen of elastin-associated microfibrils', 'Extra-cellular matrix', 'Extra-cellular matrix, TGF beta receptor complex assembly', 'Type IV membrane protein in plasma and intracellular vesicle membranes', 'Transmembrane glycoprotein', 'Extra-cellular matrix, cell adhesion, cell migration', 'Endoplasmatic reticulum membrane protein, translocation', 'Cell adhesion, calcium ion binding', 'Endoplasmatic reticulum, calcium ion binding', 'Type I integral membrane glycoprotein', 'Cell adhesion, member RAS oncogene family', 'Extra-cellular matrix, calcium ion binding', 'Extra-cellular matrix, cell adhesion, signal transduction', 'Extra-cellular matrix, cell adhesion', 'Extra-cellular matrix', 'Extra-cellular, insulin-like growth factor binding protein 7', 'Extra-cellular matrix, complement pathway'],
}, index=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])
