import pandas as pd

df = pd.DataFrame({
    '': ['1', '6', '18', '2', '7', '19', '3', '8', '20', '4', '9', '21', '5', '10', '22', '', '11', '23', '', '12', '24', '', '13', '25', '', '14', '26', '', '15', '27', '', '16', '28', '', '17', '', '', '', '', '', '', '', '1', '', '', '2', '', '', '3', '', '', '4', '', '', '5', '', '', '6', '', '', '7', '', '', '8', '', ''],
    'Known SRF target Genes': ['Jun-B', 'serum response factor', 'fos-like antigen 1', 'tropomyosin 1, alpha', 'vinculin', '', '', '', '', '', '', '', 'MKL-Independent genes (122)', 'Known SRF target genes', 'cysteine rich protein 61 ( Cyr61 )', 'thrombospondin 1', 'FBJ osteosarcoma oncogene ( c-fos )', 'FBJ osteosarcoma oncogene B ( FosB )', 'cysteine rich protein 1 ( Crp1 )', 'prostaglandin-endoperoxide synthase 2', 'early growth response 1 ( Egr1 )', 'early growth response 2 ( Egr2 )'],
    '': ['1', '6', '18', '2', '7', '19', '3', '8', '20', '4', '9', '21', '5', '10', '22', '', '11', '23', '', '12', '24', '', '13', '25', '', '14', '26', '', '15', '27', '', '16', '28', '', '17', '', '', '', '', '', '', '', '1', '', '', '2', '', '', '3', '', '', '4', '', '', '5', '', '', '6', '', '', '7', '', '', '8', '', ''],
    'Other Genes': ['adrenomedullin', 'Adenosine A2b receptor', 'B-cell translocation gene 2', 'Coagulation factor III', 'CDC42 effector protein 3', 'Leukemia Inhibitory factor', 'enigma homolog', 'Retinoblastoma inhibiting gene 1', 'epiregulin', 'TGFβ inducible early growth response', 'hexokinase 2', 'Tribbles Homolog 1', 'inhibitor of DNA binding 3', 'Aortic alpha actin-2', 'interleukin 6', 'expressed sequence AA939927', 'pleckstrin homology-like domain, family A', 'transmembrane 4 superfamily member 10 homolog', 'similar to Hs Mig6', 'methionine adenosyltransferase II, alpha', 'snail homolog 1', 'ELL-related RNA polymerase II, elongation factor', 'zyxin', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    '': ['1', '6', '18', '2', '7', '19', '3', '8', '20', '4', '9', '21', '5', '10', '22', '', '11', '23', '', '12', '24', '', '13', '25', '', '14', '26', '', '15', '27', '', '16', '28', '', '17', '', '', '', '', '', '', '', '1', '', '', '2', '', '', '3', '', '', '4', '', '', '5', '', '', '6', '', '', '7', '', '', '8', '', ''],
    'Other Genes': ['adrenomedullin', 'Adenosine A2b receptor', 'B-cell translocation gene 2', 'Coagulation factor III', 'CDC42 effector protein 3', 'Leukemia Inhibitory factor', 'enigma homolog', 'Retinoblastoma inhibiting gene 1', 'epiregulin', 'TGFβ inducible early growth response', 'hexokinase 2', 'Tribbles Homolog 1', 'inhibitor of DNA binding 3', 'Aortic alpha actin-2', 'interleukin 6', 'expressed sequence AA939927', 'pleckstrin homology-like domain, family A', 'transmembrane 4 superfamily member 10 homolog', 'similar to Hs Mig6', 'methionine adenosyltransferase II, alpha', 'snail homolog 1', 'ELL-related RNA polymerase II, elongation factor', 'zyxin', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
}, index=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])
