import pandas as pd

df = pd.DataFrame({
    'Gene': ['RAC1', 'TIMP1', 'TGFβR II', 'βGLOGIN', 'PI3K', 'ERK3', 'VIMENTIN', 'FTP', 'ADIPSIN', 'EEF1A1'],
    'Forward Sequence': ['CACGATCGAGAAACTGAAGGA', 'TACTTCCACAGGTCCCACAAC', 'CAGCGTTTCAAAAAGTGAAGC', 'GCAACCTCAGACAGACACCAT', 'TGAGCAAGAGGCTTTGGAGTA', 'GAGCCAGTAGAGGATGGGAAG', 'ATCGATGTGGATGTTTCCAAG', 'ATCCCTTAGCATCAGCTCCTC', 'CCTGCATCTGGTTGGTCTTTA', 'GATGCATTGTTATCATTAACC'],
    'Reverse Sequence': ['AGCAGGCATTTTCTCTTCCTC', 'GTTTGCAGGGGATGGATAAAC', 'CTAGACTGGGGTCCAGGTAGG', 'ACCTTAGGGTTGCCCATAACA', 'TTCCTATGCAATCGGTCTTTG', 'GATGAGGAATTTGAGGGGAAG', 'TGTCTCCGGTACTCAGTGGAC', 'CGTTCTTTTGGCATTAGTTGG', 'AGCCTCCTGAGTAGCTGGAAC', 'CATGCAAGTTTGCTGAGCTG'],
}, index=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
